#!/usr/bin/env node
/**
 * atlas-sync — regenerates the atlas/ snapshot.
 *
 *   node scripts/atlas-sync.mjs                      # repo-derived refresh (no Figma)
 *   node scripts/atlas-sync.mjs --pull <file.json>   # merge a Figma MCP pull, stamp syncedAt
 *   node scripts/atlas-sync.mjs --check              # report only, write nothing (exit 1 on drift)
 *
 * The agent-facing half of this lives in .agents/skills/atlas-figma-sync/.
 * The pull file is produced by that skill from Figma MCP calls; its shape is
 * documented in references/mcp-pull.md. This script never talks to Figma and
 * never writes to Figma.
 */

import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const SRC = path.join(ROOT, "packages/ui-web/src")
const CC = path.join(ROOT, "packages/figma-sync/code-connect")
const TOKENS_CSS = path.join(ROOT, "packages/tokens/atlas.tokens.css")
const ATLAS = path.join(ROOT, "atlas")
const FILE_KEY = "cKYhfaHLCoyMHi9nKr63Ig"

/** Display order for index.md — tiers in AGENTS.md §4 order. */
const ORDER = [
  "Button", "Input", "Label", "Textarea", "Checkbox", "Switch", "Badge",
  "Alert", "Card", "Dialog", "Tabs", "NavBar",
]
/** Layout/platform groups; also rendered into a generated section of atlas/tokens.md. */
const LAYOUT_GROUPS = {
  "Typography families and letter spacing": ["font-sans", "font-arabic", "font-mono", "letter-spacing-"],
  "Layout grid": ["breakpoint-", "container-", "columns", "gutter", "margin"],
  "Dialog widths": ["dialog-"],
  "Safe area": ["safe-"],
  "Z-index": ["z-"],
}

/** Scale groups kept in tokens.json, in this order; file order within a group. */
const SCALE_PREFIXES = [
  "spacing-", "radius-", "font-size-", "text-", "font-weight-", "line-height-",
  "duration-", "easing-", "shadow-", "border-width-", "opacity-", "touch-",
  ...Object.values(LAYOUT_GROUPS).flat(),
]

/* ── args ───────────────────────────────────────────────── */

const args = process.argv.slice(2)
const flag = (n) => args.includes(n)
const opt = (n) => { const i = args.indexOf(n); return i === -1 ? null : args[i + 1] }
const CHECK = flag("--check")
const PULL_PATH = opt("--pull")

/* ── small helpers ──────────────────────────────────────── */

const read = (p) => fs.readFileSync(p, "utf8")
const uniqSort = (a) => [...new Set(a)].sort()
const today = () => new Date().toISOString()

const written = []
function write(rel, content) {
  const abs = path.join(ROOT, rel)
  const before = fs.existsSync(abs) ? read(abs) : null
  if (before === content) return
  if (!CHECK) fs.writeFileSync(abs, content)
  written.push(rel)
}

/**
 * JSON that stays cheap to read: leaf arrays and flat objects collapse onto one
 * line. Token cost of the snapshot is the whole point of this layer.
 */
function compactJson(value) {
  let out = JSON.stringify(value, null, 2)
  const pass = (re, fit) => {
    let prev
    do {
      prev = out
      out = out.replace(re, (m, open, inner, close) => {
        const one = `${open}${open === "[" ? "" : " "}${inner.split("\n").map((l) => l.trim()).join(" ")}${open === "[" ? "" : " "}${close}`
        return fit(one) ? one : m
      })
    } while (out !== prev)
  }
  // leaf arrays (no nested structure) always collapse — one long line is cheaper to read than 40 short ones
  pass(/(\[)\n\s*([^[\]{}]*?)\n\s*(\])/g, () => true)
  // flat objects collapse when they stay short
  pass(/(\{)\n\s*([^{}]*?)\n\s*(\})/g, (one) => one.length <= 160)
  return out + "\n"
}

function stamp(source, syncedAt, figmaVersion) {
  return syncedAt
    ? `GENERATED — do not hand-edit. figma-synced ${syncedAt}; regenerated by atlas-figma-sync.`
    : `GENERATED — do not hand-edit. ${source}; regenerated by atlas-figma-sync.`
}

/* ── repo extraction ────────────────────────────────────── */

function components() {
  const out = []
  for (const tier of ["primitives", "compositions", "patterns", "layouts"]) {
    const dir = path.join(SRC, tier)
    if (!fs.existsSync(dir)) continue
    for (const name of fs.readdirSync(dir).sort()) {
      const tsx = path.join(dir, name, `${name}.tsx`)
      if (fs.existsSync(tsx)) out.push({ name, tier, dir: path.join(dir, name), tsx })
    }
  }
  return out.sort((a, b) => {
    const ia = ORDER.indexOf(a.name), ib = ORDER.indexOf(b.name)
    return (ia === -1 ? 99 : ia) - (ib === -1 ? 99 : ib) || a.name.localeCompare(b.name)
  })
}

/** `export type XVariant = "a" | "b"` (single- or multi-line) → ["a","b"] */
function union(src, typeName) {
  const m = src.match(new RegExp(`export type ${typeName}\\s*=([^;]*?)(?:\\n\\n|\\nexport|$)`, "s"))
  if (!m) return null
  const values = [...m[1].matchAll(/"([^"]+)"/g)].map((x) => x[1])
  return values.length ? values : null
}

/** own members of `export interface XProps { ... }` (comments stripped) */
function props(src, typeName) {
  const start = src.indexOf(`export interface ${typeName}`)
  if (start === -1) return []
  const open = src.indexOf("{", start)
  let depth = 0, end = open
  for (let i = open; i < src.length; i++) {
    if (src[i] === "{") depth++
    else if (src[i] === "}") { depth--; if (depth === 0) { end = i; break } }
  }
  const body = src
    .slice(open + 1, end)
    .replace(/\/\*\*[\s\S]*?\*\//g, "")   // jsdoc
    .replace(/\/\/[^\n]*/g, "")           // line comments
  const out = []
  // one member per line: `name?: type` — types here never span lines in this repo
  for (const line of body.split("\n")) {
    const m = line.match(/^\s*(["']?[a-zA-Z][\w-]*["']?)(\?)?\s*:\s*(.+?)\s*$/)
    if (!m) continue
    const type = m[3].replace(/[;,]\s*$/, "").trim()
    if (!type) continue
    out.push({ name: m[1].replace(/["']/g, ""), required: !m[2], type })
  }
  return out
}

/** native element a Props interface extends, e.g. `button (omits size)` — null when it extends nothing */
function nativeBase(src, typeName) {
  const start = src.indexOf(`export interface ${typeName}`)
  if (start === -1) return null
  const head = src.slice(start, src.indexOf("{", start))
  const el = head.match(/React\.\w*HTMLAttributes<HTML(\w+?)Element>/)
  if (!el) return null
  const tag = { Anchor: "a", Paragraph: "p", Heading: "h2", TextArea: "textarea", Div: "div" }[el[1]] ?? el[1].toLowerCase()
  const omitted = [...(head.match(/,\s*((?:"[^"]+"\s*\|?\s*)+)>/)?.[1] ?? "").matchAll(/"([^"]+)"/g)].map((m) => m[1])
  return `native \`<${tag}>\` attributes${omitted.length ? ` (except ${omitted.join(", ")})` : ""}`
}

/** replace the text between two marker comments, or append the block when the markers are absent */
function upsertSection(body, begin, end, block) {
  const at = body.indexOf(begin)
  return at === -1
    ? `${body.trimEnd()}\n\n${block}\n`
    : `${body.slice(0, at)}${block}${body.slice(body.indexOf(end) + end.length)}`
}

function subcomponents(src, name) {
  const found = [
    ...src.matchAll(/export (?:function|const) (\w+)/g),
  ].map((m) => m[1])
  return found.filter((n) => n !== name && n.startsWith(name) && !/Props$/.test(n) && !/^(\w+)(Variant|Size|Intent|Side|Resize)$/.test(n))
}

function tokensUsed(dir) {
  const found = []
  for (const f of fs.readdirSync(dir)) {
    if (!/\.(tsx|css)$/.test(f)) continue
    for (const m of read(path.join(dir, f)).matchAll(/--atlas-[a-zA-Z0-9_]+(?:-[a-zA-Z0-9_]+)*/g)) {
      if (!m[0].startsWith("--atlas-color-")) found.push(m[0])
    }
  }
  return uniqSort(found)
}

/** node id + the Figma property enums code believes in, from Code Connect */
function codeConnect(name) {
  const p = path.join(CC, `${name}.figma.tsx`)
  if (!fs.existsSync(p)) return { nodeId: null, enums: {} }
  const src = read(p)
  const node = src.match(/node-id=([\d]+)-([\d]+)/)
  const enums = {}
  for (const m of src.matchAll(/figma\.enum\(\s*"([^"]+)"\s*,\s*\{([\s\S]*?)\}\s*\)/g)) {
    enums[m[1]] = [...m[2].matchAll(/(?:^|\n)\s*"?([\w-]+)"?\s*:/g)].map((x) => x[1])
  }
  return { nodeId: node ? `${node[1]}:${node[2]}` : null, enums }
}

/* ── tokens ─────────────────────────────────────────────── */

function tokens() {
  const css = read(TOKENS_CSS)
  const semanticBlock = css.slice(
    css.indexOf("Semantic · Light"),
    css.indexOf("Dark theme override"),
  )
  const semantic = {}
  for (const m of semanticBlock.matchAll(/(--atlas-[\w-]+):\s*([^;]+);/g)) semantic[m[1]] = m[2].trim()

  const all = {}
  for (const m of css.matchAll(/(--atlas-[\w-]+):\s*([^;]+);/g)) if (!(m[1] in all)) all[m[1]] = m[2].trim()
  const scales = {}
  for (const prefix of SCALE_PREFIXES) {
    for (const [k, v] of Object.entries(all)) {
      if (k.startsWith(`--atlas-${prefix}`) && !(k in semantic)) scales[k] = v
    }
  }
  return { semantic, scales }
}

/* ── build ──────────────────────────────────────────────── */

/**
 * Without --pull we refresh repo-derived facts only. Figma facts already in the
 * snapshot are carried forward verbatim — a run with no Figma access must never
 * silently downgrade a synced snapshot back to repo-derived.
 */
function carriedForward() {
  const dir = path.join(ATLAS, "metadata")
  if (!fs.existsSync(dir)) return null
  const components = {}
  let syncedAt = null, figmaVersion = null
  for (const f of fs.readdirSync(dir)) {
    const m = JSON.parse(read(path.join(dir, f)))
    if (!m.syncedAt) continue
    syncedAt = syncedAt ?? m.syncedAt
    figmaVersion = figmaVersion ?? m.figmaVersion
    components[m.name] = { nodeId: m.figmaNodeId, properties: m.figmaProperties ?? undefined }
  }
  return syncedAt ? { fileKey: FILE_KEY, pulledAt: syncedAt, figmaVersion, components, carried: true } : null
}

const pull = PULL_PATH ? JSON.parse(read(path.resolve(ROOT, PULL_PATH))) : carriedForward()
if (pull && pull.fileKey !== FILE_KEY) {
  console.error(`✗ pull file is for Figma file ${pull.fileKey}, expected ${FILE_KEY}`)
  process.exit(1)
}
const syncedAt = pull ? (pull.pulledAt || today()) : null
const figmaVersion = pull ? (pull.figmaVersion ?? null) : null
// carried-forward facts are the same facts: the nuance belongs in the report, not in every file
const source = pull ? "figma-synced" : "repo-derived"
const HEADER = stamp(source, syncedAt, figmaVersion)

const comps = components().map((c) => {
  const src = read(c.tsx)
  const { nodeId, enums } = codeConnect(c.name)
  const figma = pull?.components?.[c.name] ?? null
  return {
    ...c,
    variants: union(src, `${c.name}Variant`),
    sizes: union(src, `${c.name}Size`),
    props: props(src, `${c.name}Props`),
    subcomponents: subcomponents(src, c.name),
    api: [c.name, ...subcomponents(src, c.name)].map((n) => ({
      name: n, props: props(src, `${n}Props`), base: nativeBase(src, `${n}Props`),
    })),
    tokensUsed: tokensUsed(c.dir),
    nodeId: figma?.nodeId ?? nodeId,
    ccEnums: enums,
    figma,
  }
})

/* ── drift detection ────────────────────────────────────── */

const drift = []
/** detectors that actually ran this pass — only their entries may be auto-closed */
const detectors = new Set(["sync:code-connect"])
if (pull) detectors.add("sync:figma")
// descriptions are only checked when the pull actually carried some
if (Object.values(pull?.components ?? {}).some((c) => c?.description)) detectors.add("sync:description")
const D = (component, side, issue, resolution, detectedBy) =>
  drift.push({ component, side, issue, resolution, detectedBy })
const setEq = (a, b) => a.length === b.length && a.every((x) => b.includes(x))

for (const c of comps) {
  // repo-internal: Code Connect maps values code does not export
  for (const [prop, values] of Object.entries(c.ccEnums)) {
    const codeValues = prop === "Variant" ? c.variants : prop === "Size" ? c.sizes : null
    if (!codeValues) continue
    const mapped = values.filter((v) => !codeValues.includes(v) && !["disabled", "unchecked", "checked", "indeterminate"].includes(v))
    if (mapped.length) {
      D(c.name, "code", `Code Connect maps ${prop} value(s) ${mapped.join(", ")} that ${c.name}${prop} does not export.`,
        `add ${mapped.join(", ")} to ${c.name}${prop}, or fix the Code Connect enum`, "sync:code-connect")
    }
  }
  if (!c.figma) {
    if (pull) D(c.name, "figma", "Component exists in code but was not found in the Figma pull.", "publish the component in Figma, or remove it from code", "sync:figma")
    continue
  }
  const fVariants = c.figma.properties?.Variant ?? null
  const fSizes = c.figma.properties?.Size ?? null
  // one side models an axis the other does not
  if (!fVariants && c.variants) {
    D(c.name, "figma", `Code has Variant ${c.variants.join(", ")}; Figma has no Variant property.`,
      `add the Variant property in Figma, or drop ${c.name}Variant`, "sync:figma")
  }
  if (fVariants && !c.variants) {
    D(c.name, "code", `Figma has Variant ${fVariants.join(", ")}; code exports no ${c.name}Variant.`,
      `add ${c.name}Variant, or — if the values are a value rather than a style — split them out in Figma (DEC-003)`, "sync:figma")
  }
  if (fVariants && c.variants && !setEq(fVariants, c.variants)) {
    const onlyFigma = fVariants.filter((v) => !c.variants.includes(v))
    const onlyCode = c.variants.filter((v) => !fVariants.includes(v))
    D(c.name, onlyFigma.length && onlyCode.length ? "both" : onlyFigma.length ? "code" : "figma",
      `Variant mismatch — Figma: ${fVariants.join(", ")} · code: ${c.variants.join(", ")}.`,
      [onlyFigma.length ? `add ${onlyFigma.join(", ")} to ${c.name}Variant` : null,
       onlyCode.length ? `add Variant ${onlyCode.join(", ")} in Figma` : null].filter(Boolean).join("; "), "sync:figma")
  }
  if (fSizes && c.sizes && !setEq(fSizes, c.sizes)) {
    const onlyFigma = fSizes.filter((v) => !c.sizes.includes(v))
    const onlyCode = c.sizes.filter((v) => !fSizes.includes(v))
    D(c.name, onlyFigma.length && onlyCode.length ? "both" : onlyFigma.length ? "code" : "figma",
      `Size mismatch — Figma: ${fSizes.join(", ")} · code: ${c.sizes.join(", ")}.`,
      [onlyFigma.length ? `add ${onlyFigma.join(", ")} to ${c.name}Size` : null,
       onlyCode.length ? `add Size ${onlyCode.join(", ")} in Figma` : null].filter(Boolean).join("; "), "sync:figma")
  }
  const ccNode = codeConnect(c.name).nodeId
  if (c.figma.nodeId && ccNode && c.figma.nodeId !== ccNode) {
    D(c.name, "code", `Code Connect points at node ${ccNode}; Figma reports ${c.figma.nodeId}.`,
      `update the node id in packages/figma-sync/code-connect/${c.name}.figma.tsx`, "sync:figma")
  }
}
if (pull) {
  for (const name of Object.keys(pull.components ?? {})) {
    if (!comps.some((c) => c.name === name)) {
      D(name, "code", "Component exists in Figma but not in packages/ui-web/src.", "implement it, or log it in state/candidates.json", "sync:figma")
    }
  }
}

/* ── metadata/<Name>.json ───────────────────────────────── */

for (const c of comps) {
  const json = {
    _generated: HEADER,
    name: c.name,
    tier: c.tier,
    import: `@atlas/ui-web/${c.tier}/${c.name}/${c.name}`,
    variants: c.variants ?? [],
    sizes: c.sizes ?? [],
    props: c.props,
    subcomponents: c.subcomponents,
    tokensUsed: c.tokensUsed,
    figmaNodeId: c.nodeId,
    figmaFileKey: FILE_KEY,
    figmaProperties: c.figma?.properties ?? null,
    syncedAt,
    figmaVersion,
    source,
  }
  write(`atlas/metadata/${c.name}.json`, compactJson(json))
}

/* ── index.md ───────────────────────────────────────────── */

const missing = ["Avatar", "Table", "Tooltip", "Select", "Radio", "Toast"].filter((n) => !comps.some((c) => c.name === n))
write("atlas/index.md", [
  `<!-- ${HEADER} -->`,
  "",
  "# Atlas components",
  "",
  "One line per component. Read `atlas/<Name>.md` only for the components you will use.",
  "",
  "| Component | Tier | Import | Variants | Sizes |",
  "|---|---|---|---|---|",
  ...comps.map((c) =>
    `| ${c.name} | ${c.tier} | \`@atlas/ui-web/${c.tier}/${c.name}/${c.name}\` | ${(c.variants ?? []).join(", ") || "—"} | ${(c.sizes ?? []).join(", ") || "—"} |`),
  "",
  `No ${missing.slice(0, -1).join(", ")} or ${missing.at(-1)} exists. Compose gaps from primitives and log them in \`state/candidates.json\`.`,
  "",
].join("\n"))

/* ── <Name>.md ──────────────────────────────────────────── */

/**
 * A Figma description replaces the repo-written guidance only when it IS guidance.
 * A spec summary ("3 variants × 3 sizes") is a Figma content gap, not documentation:
 * keep the existing doc and file the gap as a discrepancy.
 */
const isGuidance = (d) => /when to use|when not to/i.test(d) || d.length >= 200

// Every component doc carries a generated API block (import, props, subcomponents) so a prototype
// never has to open component source for a prop name.
const API_BEGIN = "<!-- BEGIN:generated-api -->"
const API_END = "<!-- END:generated-api -->"
const apiSection = (c) => [
  API_BEGIN,
  "",
  "## API",
  "```tsx",
  `import { ${c.api.map((a) => a.name).join(", ")} } from "@atlas/ui-web/${c.tier}/${c.name}/${c.name}"`,
  "```",
  ...c.api.flatMap((a) => [
    "",
    `**${a.name}**${a.base ? ` — also accepts ${a.base}` : ""}`,
    ...(a.props.length ? a.props.map((p) => `- \`${p.name}${p.required ? "" : "?"}: ${p.type}\``) : ["- no own props"]),
  ]),
  API_END,
].join("\n")

const docsReplaced = []
for (const c of comps) {
  const rel = `atlas/${c.name}.md`
  const abs = path.join(ROOT, rel)
  const raw = c.figma?.description?.trim()
  if (raw && !isGuidance(raw)) {
    D(c.name, "figma", `Figma description is a spec summary, not usage guidance: "${raw}".`,
      "rewrite the Figma description as what it is · when to use · when not to use · do/don't (phase 3)", "sync:description")
  }
  const description = raw && isGuidance(raw) ? raw : null
  if (description) {
    docsReplaced.push(c.name)
    write(rel, [
      `<!-- ${HEADER} -->`,
      "",
      `# ${c.name}`,
      description,
      "",
      "## Variants",
      (c.variants ?? []).join(" · ") || "—",
      "",
      "## Sizes",
      (c.sizes ?? []).join(" · ") || "—",
      "",
      apiSection(c),
      "",
    ].join("\n"))
  } else if (fs.existsSync(abs)) {
    // no Figma description yet — keep the existing guidance, refresh the stamp and the API block
    const body = read(abs).replace(/^<!-- GENERATED[^>]*-->/, `<!-- ${HEADER} -->`)
    write(rel, upsertSection(body, API_BEGIN, API_END, apiSection(c)))
  }
}

/* ── tokens ─────────────────────────────────────────────── */

const tok = tokens()
// Figma MCP exposes variables per node, not a full variable table, so tokens stay
// repo-derived from packages/tokens/atlas.tokens.css until a pull carries variables.
const tokenSource = pull?.variables ? source : "repo-derived (packages/tokens/atlas.tokens.css)"
write("atlas/tokens.json", compactJson({
  _generated: stamp(tokenSource, pull?.variables ? syncedAt : null),
  source: tokenSource,
  syncedAt: pull?.variables ? syncedAt : null,
  figmaVersion: pull?.variables ? figmaVersion : null,
  note: "Semantic tokens and layout scales only. Primitive colour ramps (--atlas-color-*) are never used in app code.",
  semantic: tok.semantic,
  scales: tok.scales,
}))

// tokens.md keeps its curated body; the layout/platform groups are rendered between markers
const LAYOUT_BEGIN = "<!-- BEGIN:generated-layout-tokens -->"
const LAYOUT_END = "<!-- END:generated-layout-tokens -->"
const layoutSection = [
  LAYOUT_BEGIN,
  ...Object.entries(LAYOUT_GROUPS).flatMap(([title, prefixes]) => [
    "", `## ${title}`,
    prefixes.map((p) => Object.entries(tok.scales)
      .filter(([k]) => k.startsWith(`--atlas-${p}`))
      .map(([k, v]) => `\`${k.slice(8)}\` ${v}`).join(" · ")).filter(Boolean).join("\n"),
  ]),
  LAYOUT_END,
].join("\n")

for (const rel of ["atlas/tokens.md", "atlas/README.md"]) {
  const abs = path.join(ROOT, rel)
  if (!fs.existsSync(abs)) continue
  let body = read(abs).replace(/^<!-- GENERATED[^>]*-->/, `<!-- ${HEADER} -->`)
  if (rel === "atlas/tokens.md") {
    body = upsertSection(body, LAYOUT_BEGIN, LAYOUT_END, layoutSection)
  }
  write(rel, body)
}

/* ── state/discrepancies.json ───────────────────────────── */

const discPath = path.join(ATLAS, "state/discrepancies.json")
const disc = JSON.parse(read(discPath))
const existing = disc.discrepancies ?? []
const nextId = () => {
  const max = Math.max(0, ...existing.map((d) => parseInt(String(d.id).replace(/\D/g, ""), 10) || 0))
  return `DISC-${String(max + 1).padStart(3, "0")}`
}
const sameAs = (a, b) => a.component === b.component && a.issue === b.issue

for (const d of drift) {
  const hit = existing.find((e) => sameAs(e, d))
  if (hit) {
    hit.status = "open"
    hit.side = d.side
    hit.resolution = d.resolution
    hit.detectedBy = d.detectedBy
    hit.lastSeen = syncedAt ?? today()
  } else {
    existing.push({ id: nextId(), component: d.component, side: d.side, status: "open",
      issue: d.issue, resolution: d.resolution, detectedBy: d.detectedBy,
      firstSeen: syncedAt ?? today(), lastSeen: syncedAt ?? today() })
  }
}
// sync-detected entries that no longer drift are closed by the sync
const autoClosed = []
for (const e of existing) {
  if (detectors.has(e.detectedBy) && e.status === "open" && !drift.some((d) => sameAs(e, d))) {
    e.status = "closed"
    e.closedAt = syncedAt ?? today()
    e.closedBy = e.detectedBy
    autoClosed.push(e.id)
  }
}
write("atlas/state/discrepancies.json", compactJson({
  ...disc, _generated: HEADER, syncedAt, figmaVersion, discrepancies: existing,
}))

/* ── state stamps ───────────────────────────────────────── */

// state files are repo state, not Figma content — the stamp records only when the sync ran
for (const name of ["status", "decisions", "candidates"]) {
  const rel = `atlas/state/${name}.json`
  const json = JSON.parse(read(path.join(ROOT, rel)))
  write(rel, compactJson({
    ...json,
    _generated: `GENERATED — do not hand-edit. regenerated by atlas-figma-sync${syncedAt ? ` at ${syncedAt}` : ""}.`,
    syncedAt, figmaVersion,
  }))
}

/* ── report ─────────────────────────────────────────────── */

const openDrift = existing.filter((e) => e.status === "open")
console.log(`atlas-sync — ${PULL_PATH ? `figma pull ${PULL_PATH}` : pull ? "no pull; Figma facts carried forward from the last sync" : "repo-derived (never synced)"}`)
console.log(`  source       ${source}`)
console.log(`  syncedAt     ${syncedAt ?? "null (never read from Figma)"}`)
console.log(`  figmaVersion ${figmaVersion ?? "null"}`)
console.log(`  components   ${comps.length}${pull ? ` (${Object.keys(pull.components ?? {}).length} in pull)` : ""}`)
console.log(`  ${CHECK ? "would write" : "written"}    ${written.length} file(s)`)
for (const f of written) console.log(`    · ${f}`)
if (docsReplaced.length) console.log(`  docs from Figma descriptions: ${docsReplaced.join(", ")}`)
if (autoClosed.length) console.log(`  closed by this sync: ${autoClosed.join(", ")}`)
console.log(`\n  drift — ${drift.length} detected this run, ${openDrift.length} open in state/discrepancies.json`)
for (const d of openDrift) console.log(`    ${d.id} ${d.component} [${d.side}] ${d.issue}`)
if (!PULL_PATH) console.log(`\n  ⚠ no --pull: Figma-side facts were ${pull ? `last read ${syncedAt}` : "never read"} — re-run the atlas-figma-sync skill to refresh them.`)
if (CHECK && (drift.length || written.length)) process.exit(1)
